---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-pvc-development"
  labels:
    app: "mongo-development"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
